# Generated by Django 3.2.15 on 2022-10-19 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_community_control', '0002_communitypostmodel_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPostCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Post Comment',
                'verbose_name_plural': 'Community Post Comments',
            },
        ),
        migrations.AddField(
            model_name='communitypostmodel',
            name='totalCommentCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitypostmodel',
            name='totalLikeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CommunityPostLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_community_control.communitypostmodel')),
            ],
            options={
                'verbose_name': 'Community Post Like',
                'verbose_name_plural': 'Community Post Likes',
            },
        ),
        migrations.CreateModel(
            name='CommunityPostCommentReplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_community_control.communitypostcommentmodel')),
            ],
            options={
                'verbose_name': 'Community Post Comment Reply',
                'verbose_name_plural': 'Community Post Comment Replies',
            },
        ),
        migrations.AddField(
            model_name='communitypostcommentmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_community_control.communitypostmodel'),
        ),
    ]
