# Generated by Django 3.2.15 on 2022-10-19 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_community_control', '0003_auto_20221020_0219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityPostCommentReplyModel',
        ),
    ]
