# Generated by Django 3.2.15 on 2022-10-20 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0002_auto_20221020_0219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingModel',
        ),
    ]
