# Generated by Django 3.2.13 on 2022-05-10 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ot_control', '0001_initial'),
        ('user_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otschedulemodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_control.patientmodel'),
        ),
    ]
