# Generated by Django 3.2.15 on 2022-10-19 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article_control', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article Comment',
                'verbose_name_plural': 'Article Comments',
            },
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='totalCommentCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='totalLikeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ArticleLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_control.articlemodel')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article Like',
                'verbose_name_plural': 'Article Likes',
            },
        ),
        migrations.CreateModel(
            name='ArticleCommentReplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articleComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_control.articlecommentmodel')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article Comment Reply',
                'verbose_name_plural': 'Article Comment Replies',
            },
        ),
        migrations.AddField(
            model_name='articlecommentmodel',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_control.articlemodel'),
        ),
        migrations.AddField(
            model_name='articlecommentmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
