# Generated by Django 3.2.15 on 2022-10-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storemodel',
            options={'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AddField(
            model_name='storemodel',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='storemodel',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
