# Generated by Django 3.2.15 on 2022-10-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store_control', '0002_auto_20221016_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
    ]
