GENDER_CHOICES = [
    ("", "Select Gender"),
    ("Male", "Male"),
    ("Female", "Female"),
    ("Other", "Other"),
]
BLOOD_GROUP_CHOICES = [
    ("", "Select Blood Group"),
    ("A+", "A+"),
    ("A-", "A-"),
    ("B+", "B+"),
    ("B-", "B-"),
    ("AB+", "AB+"),
    ("AB-", "AB-"),
    ("O+", "O+"),
    ("O-", "O-"),
]
STATUS_CHOICES = [
    ("", "Select Status"),
    ("Pending", "Pending"),
    ("Approved", "Approved"),
    ("Completed", "Completed"),
    ("In Progress", "In Progress"),
    ("Rejected", "Rejected"),
]
ORDER_STATUS_CHOICES = [
    ("", "Select Status"),
    ("Pending", "Pending"),
    ("Approved", "Approved"),
    ("Completed", "Completed"),
    ("In Progress", "In Progress"),
    ("Rejected", "Rejected"),
]
PAYMENT_METHOD_CHOICES = [  # A list of payment methods
    ("", "Payment Method"),
    ("Cash on Delivery", "Cash on Delivery"),
    ("bKash", "bKash"),
    ("Nagad", "Nagad"),
]
HISTORY_TYPE_CHOICES = [
    ("", "Select History Type"),
    ("X-Ray", "X-Ray"),
    ("Blood Test", "Blood Test"),
    ("Ultrasound", "Ultrasound"),
    ("ECG", "ECG"),
    ("MRI", "MRI"),
    ("CT Scan", "CT Scan"),
    ("Other", "Other"),
]
TYPES_CHOICES = [
    ("", "Select Ambulance Type"),
    ("Standard", "Standard"),
    ("AC", "AC"),
    ("Cardiac", "Cardiac"),
    ("ICU", "ICU"),
    ("Freezer", "Freezer"),
]
MEDICINE_TYPE_CHOICES = [
    ("", "Select Medicine Type"),
    ("Tablet", "Tablet"),
    ("Capsule", "Capsule"),
    ("Syrup", "Syrup"),
    ("Injection", "Injection"),
    ("Drops", "Drops"),
    ("Cream", "Cream"),
    ("Ointment", "Ointment"),
    ("Powder", "Powder"),
    ("Lotion", "Lotion"),
    ("Gel", "Gel"),
    ("Aerosols", "Aerosols"),
    ("Suspension", "Suspension"),
    ("Solution", "Solution"),
    ("Inhaler", "Inhaler"),
]
CITY_CHOICES = [
    ("", "Select City"),
    ("Bagerhat", "Bagerhat"),
    ("Bandarban", "Bandarban"),
    ("Barguna", "Barguna"),
    ("Barishal", "Barishal"),
    ("Bhola", "Bhola"),
    ("Bogura", "Bogura"),
    ("Brahmanbaria", "Brahmanbaria"),
    ("Chandpur", "Chandpur"),
    ("Chapainawabganj", "Chapainawabganj"),
    ("Chattogram", "Chattogram"),
    ("Chuadanga", "Chuadanga"),
    ("Cox’s Bazar", "Cox’s Bazar"),
    ("Cumilla", "Cumilla"),
    ("Dhaka", "Dhaka"),
    ("Dinajpur", "Dinajpur"),
    ("Faridpur", "Faridpur"),
    ("Feni", "Feni"),
    ("Gaibandha", "Gaibandha"),
    ("Gazipur", "Gazipur"),
    ("Gopalganj", "Gopalganj"),
    ("Habiganj", "Habiganj"),
    ("Jamalpur", "Jamalpur"),
    ("Jashore", "Jashore"),
    ("Jhalokati", "Jhalokati"),
    ("Jhenaidah", "Jhenaidah"),
    ("Joypurhat", "Joypurhat"),
    ("Khagrachhari", "Khagrachhari"),
    ("Khulna", "Khulna"),
    ("Kishoreganj", "Kishoreganj"),
    ("Kushtia", "Kushtia"),
    ("Kurigram", "Kurigram"),
    ("Lakshmipur", "Lakshmipur"),
    ("Lalmonirhat", "Lalmonirhat"),
    ("Madaripur", "Madaripur"),
    ("Magura", "Magura"),
    ("Manikganj", "Manikganj"),
    ("Meherpur", "Meherpur"),
    ("Moulvibazar", "Moulvibazar"),
    ("Munshiganj", "Munshiganj"),
    ("Mymensingh", "Mymensingh"),
    ("Naogaon", "Naogaon"),
    ("Narayanganj", "Narayanganj"),
    ("Narail", "Narail"),
    ("Narsingdi", "Narsingdi"),
    ("Natore", "Natore"),
    ("Netrokona", "Netrokona"),
    ("Nilphamari", "Nilphamari"),
    ("Noakhali", "Noakhali"),
    ("Pabna", "Pabna"),
    ("Panchagarh", "Panchagarh"),
    ("Patuakhali", "Patuakhali"),
    ("Pirojpur", "Pirojpur"),
    ("Rajbari", "Rajbari"),
    ("Rajshahi", "Rajshahi"),
    ("Rangamati", "Rangamati"),
    ("Rangpur", "Rangpur"),
    ("Satkhira", "Satkhira"),
    ("Shariatpur", "Shariatpur"),
    ("Sherpur", "Sherpur"),
    ("Sirajganj", "Sirajganj"),
    ("Sunamganj", "Sunamganj"),
    ("Sylhet", "Sylhet"),
    ("Tangail", "Tangail"),
    ("Thakurgaon", "Thakurgaon"),
]
DISEASE_SYMPTOM_CHOICES = [
    ("", "Select Disease Symptom"),
    ('itching', "Itching"),
    ('skin_rash', "Skin Rash"),
    ('nodal_skin_eruptions', "Nodal Skin Eruptions"),
    ('continuous_sneezing', "Continuous Sneezing"),
    ('shivering', "Shivering"),
    ('chills', "Chills"),
    ('joint_pain', "Joint Pain"),
    ('stomach_pain', "Stomach Pain"),
    ('acidity', "Acidity"),
    ('ulcers_on_tongue', "Ulcers on Tongue"),
    ('muscle_wasting', "Muscle Wasting"),
    ('vomiting', "Vomiting"),
    ('burning_micturition', "Burning Micturition"),
    ('spotting_ urination', "Spotting  Urination"),
    ('fatigue', "Fatigue"),
    ('weight_gain', "Weight Gain"),
    ('anxiety', "Anxiety"),
    ('cold_hands_and_feets', "Cold Hands and Feets"),
    ('mood_swings', "Mood Swings"),
    ('weight_loss', "Weight Loss"),
    ('restlessness', "Restlessness"),
    ('lethargy', "Lethargy"),
    ('patches_in_throat', "Patches in Throat"),
    ('irregular_sugar_level', "Irregular Sugar Level"),
    ('cough', "Cough"),
    ('high_fever', "High Fever"),
    ('sunken_eyes', "Sunken Eyes"),
    ('breathlessness', "Breathlessness"),
    ('sweating', "Sweating"),
    ('dehydration', "Dehydration"),
    ('indigestion', "Indigestion"),
    ('headache', "Headache"),
    ('yellowish_skin', "Yellowish Skin"),
    ('dark_urine', "Dark Urine"),
    ('nausea', "Nausea"),
    ('loss_of_appetite', "Loss of Appetite"),
    ('pain_behind_the_eyes', "Pain behind the Eyes"),
    ('back_pain', "Back Pain"),
    ('constipation', "Constipation"),
    ('abdominal_pain', "Abdominal Pain"),
    ('diarrhoea', "Diarrhoea"),
    ('mild_fever', "Mild Fever"),
    ('yellow_urine', "Yellow Urine"),
    ('yellowing_of_eyes', "Yellowing of Eyes"),
    ('acute_liver_failure', "Acute Liver Failure"),
    ('fluid_overload', "Fluid Overload"),
    ('swelling_of_stomach', "Swelling of Stomach"),
    ('swelled_lymph_nodes', "Swelled Lymph Nodes"),
    ('malaise', "Malaise"),
    ('blurred_and_distorted_vision', "Blurred and Distorted Vision"),
    ('phlegm', "Phlegm"),
    ('throat_irritation', "Throat Irritation"),
    ('redness_of_eyes', "Redness of Eyes"),
    ('sinus_pressure', "Sinus Pressure"),
    ('runny_nose', "Runny Nose"),
    ('congestion', "Congestion"),
    ('chest_pain', "Chest Pain"),
    ('weakness_in_limbs', "Weakness in Limbs"),
    ('fast_heart_rate', "Fast Heart Rate"),
    ('pain_during_bowel_movements', "Pain during Bowel Movements"),
    ('pain_in_anal_region', "Pain in Anal Region"),
    ('bloody_stool', "Bloody Stool"),
    ('irritation_in_anus', "Irritation in Anus"),
    ('neck_pain', "Neck Pain"),
    ('dizziness', "Dizziness"),
#     ('cramps'),
#     ('bruising'),
#     ('obesity'),
#     ('swollen_legs'),
#     ('swollen_blood_vessels'),
#     ('puffy_face_and_eyes'),
#     ('enlarged_thyroid'),
#     ('brittle_nails'),
#     ('swollen_extremeties'),
#     ('excessive_hunger'),
#     ('extra_marital_contacts'),
#     ('drying_and_tingling_lips'),
#     ('slurred_speech'),
#     ('knee_pain'),
#     ('hip_joint_pain'),
#    ( 'muscle_weakness'),
#    ('stiff_neck'),
#    ('swelling_joints'),
#    ('movement_stiffness'),
#    ('spinning_movements'),
#    ('loss_of_balance'),
#    ('unsteadiness'),
#    ('weakness_of_one_body_side'),
#    ( 'loss_of_smell'),
#    ('bladder_discomfort'),
#    ('foul_smell_of urine'),
#    ('continuous_feel_of_urine'),
#    ('passage_of_gases'),
#    ('internal_itching'),
#    ('toxic_look_(typhos)'),
#    ( 'depression'),
#    ('irritability'),
#    ('muscle_pain'),
#    ('altered_sensorium'),
#    'red_spots_over_body','belly_pain','abnormal_menstruation','dischromic _patches',
#     'watering_from_eyes','increased_appetite','polyuria','family_history','mucoid_sputum','rusty_sputum','lack_of_concentration','visual_disturbances',
#     'receiving_blood_transfusion','receiving_unsterile_injections','coma','stomach_bleeding','distention_of_abdomen','history_of_alcohol_consumption',
#     'fluid_overload','blood_in_sputum','prominent_veins_on_calf','palpitations','painful_walking','pus_filled_pimples','blackheads','scurring','skin_peeling',
#     'silver_like_dusting','small_dents_in_nails','inflammatory_nails','blister','red_sore_around_nose','yellow_crust_ooze'
    ]
